### ISSUE TITLE
2nd round bidding should exclude 1st proposed trump suit

### ISSUE THREAD

**Issue by ln1draw** [wlindley/euchre#3]
In Euchre, for the 2nd round of bidding, you should not be able to call the suit from the first round of bidding as trump. 

If the ace of hearts is face-up for the first round of bidding and all players pass, then when the second round of bidding occurs, players are unable to call hearts as trump. This also means that it is impossible in this case for hearts to be called without giving the dealer the option to take the ace of hearts.

**Comment by wlindley** [comment]
Fixed in latest release. Now the up card's suit gets black listed in the second round of trump bidding. Sorry for the long delay, but at least it's ready for the family camp out!
